### PR TITLE
Add HTTP return code 418

### LINKED ISSUE #2: HTTP 418 missing
As defined in [section 2.3.2 of RFC 2324](https://tools.ietf.org/html/rfc2324#section-2.3.2):

> ## 418 I'm a teapot
> Any attempt to brew coffee with a teapot should result in the error code "418 I'm a teapot". The resulting entity body MAY be short and stout.

Is there any reason that the code is missing from `StatusCodeInterface`?

Even though "it is not expected to be implemented by actual HTTP servers", there are actual implementations of it (see https://stackoverflow.com/q/24018008/404623) and it is trivial to do in PHP.

### PR DESCRIPTION
**Pull request by RinkAttendant6**
Resolves #2.

### CODE REVIEW

**Comment by weierophinney** [comment]
Thanks, @RinkAttendant6\! Released with version 1.1.1.

**Comment by martinmine** [comment]
Note that the spec @RinkAttendant6 commits is actually an aprils fools. Note the date https://tools.ietf.org/html/rfc2518 also, it quotes: "This memo provides information for the Internet community. It does not specify an Internet standard of any kind.". HTTP 418 is according to IANA unassigned: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

**Comment by RinkAttendant6** [comment]
Regarding https://github.com/php-fig/http-message-util/pull/3#issuecomment-321900214

It might be a joke by the IETF, but there are certainly [sites that implement it](https://stackoverflow.com/questions/24018008/is-there-a-server-that-implements-http-status-code-418). Besides, I doubt that a future RFC would use the status code, and if there are, another change to this library would be warranted.

**Comment by martinmine** [comment]
@RinkAttendant6 where is my HTTP BREW then? :(

**Comment by RinkAttendant6** [comment]
@martinmine There's four servers that advertise support for the BREW method in their `Access-Control-Allow-Method` response header: https://www.shodan.io/search?query=BREW+http+access-control-allow-methods

**Comment by martinmine** [comment]
@RinkAttendant6 thnx

**Pull request merged**
